server:
  port: 8080

spring:
  application:
    name: eb-zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

#配置zuul网关的转发路径
zuul:
  routes:
    eb-admin: /system/**
    eb-web: /front/**

#指定ribon的读取失效时间，与连接时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
