#配置端口号
server:
  port: 8081

#配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/k10_easybuy?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  mvc:
    static-path-pattern: /static/**  #开启静态资源访问
    view:
      prefix: /pages/
      suffix: .jsp
  application:
    name: eb-admin

#配置xml形式的mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
